apiVersion: ENC[AES256_GCM,data:4fQ=,iv:7pRatiKSeJJm9GQifBdMQVby+UofjGL6e2tPJ/bNVgk=,tag:tZqehyi3HMS1Rb7NlXhzMA==,type:str]
kind: ENC[AES256_GCM,data:kIvKrRjI,iv:EUehpPpP1cDHRNYlZwx2SJZXNYHqGMsVPKBjMbpgTYk=,tag:ws9FLfVS/vaMt5OCZoMLWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QmnWPmfC7gCvntGHMeHoRjo1Qg==,iv:Np7iQqPSvHopDV/hlchCBbNcGGpeBODgcfzU0dl2L7E=,tag:lLEiN4IC1NudIy5klJW6tg==,type:str]
    namespace: ENC[AES256_GCM,data:d8isKbvzxug=,iv:tXeZZHvWD3ONg/JhWonyhIjDOeqYfHz1mhiu7ecScbQ=,tag:poEYt1SR1FKKs8Stf0H6Bg==,type:str]
type: ENC[AES256_GCM,data:/vor0bwN,iv:8cSKMLSQ4iAU1vs0pdLuKL+N1a56aZ8uAPpbXeu1row=,tag:Lva3dVxZlZkEIXDAr6pwJw==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:S6Z9JA6WgDUk2/3EZcetSxNhfTjTCg2Mjqf1aeWU/5bEYxqFed2rS8hmDoRF+IthBwECAKzWYUih4u34XqsxXA==,iv:apNUHJNuE+uj5aX4bAoFhPaGkOsscgHPHneSbut/rmQ=,tag:Fq0rMVo5n/5ljWP+V0IxoQ==,type:str]
sops:
    age:
        - recipient: age1q4amzhu35vv98c8usgamjjhwhn5q82sulmzdmcdhkh2zq0a3vaesxvv9y4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGNKd25QTXVqcmdLZWJU
            NTh5eUJNelRSM2Q0MmlWN2svOGJXL2krZlRBCkw4SjN0bDl3SXNzUWcrSXdUWGNr
            K2M0RHo0b1ZDTkRGVU41WXdrTUErMWMKLS0tIDl5azJzZVJUTkF1TTJDSTVzVG9P
            OUJtdVdaMldiT3g4TXRUQ2NJQTlFUUkKKWjaTjzKk4TvAY0LJ8Zutsa4O33810Uu
            52pBvbC1wyiTWPP209tMg1Uatn/NZ3emzpRFQJe6hfPgpuOrUYiNVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1arllsk3da07lj6ers0cdvtaz4qqlg7lq7h8k7nmp2ejtwm29pgcs0lun67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VUhqUFNHSUl0M1RMdkU3
            K2ZzazB3aXFuVWJNVnFPalBxcVFxbERlR0RNClJOOUFjek4yNkgyU2dRejQ1ZzRh
            Uk5NZnRTSTYwcXRWbjBTYWRLd3JTZmcKLS0tICsycm5QNFgvU293U21yWWJKdk9r
            MnNiVWtCeW0wWXlVTndrTWh3SzBHYlUKnK/KVU55Dpuk5ygGWqKZ2C0JSg9bL1xn
            Na5iLpq8AnMKbYC/TDooPQHBPsYBUccg2gIBbdJbNkzC9IHsv4aFjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jksv6jmy6flf0cv3grctntgs7kp53c7d72690qsxrxvawxz7nu2sttfklz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeCs1ZktHczdIS2RLZlVN
            RFY2RjlXNGdEUXZSYjdiRG5ZMTcrL0Z6dFdBCmFFeVJnVVU2a0hVU3RkaUNPcXkz
            WWRKZ0pHRGpvdG94clpCN2Y0S2R4cEEKLS0tIFNYdDFPMjdGZVpYeW5SYjZLYlQz
            RGM5RkY1YlBHVk1EbjR6UVRXcGE3ZDQKaz5GhUvTU0ellbZ0cuQ91Jc9T4Cnzt1+
            c3e/3c53a2Qv8sA3P6TwXjaHCkJB7aM+W6jHHYZy5If3sb1IM6tdCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19wdth3zh940spdq34gweu6feugejlzxeczlgjvf92nygg6tkf3lq2aprdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN2xncEdDYkhFQlE5NER4
            dXFEVjd5UDRlVEJBcExkL0RxQ2REdk9hWkM0Ci8yNkRTN01FWTY0RWFTSG45eVZn
            YktmV3Z2Nk9CSGlOU0R5Y2NyQ0JDUXcKLS0tIFZwcjB1RW8zS29GUW9SWkZkLzkv
            NGxJbzF6VHJ1VytNbHVLYXl6MHpuQm8KIxoVum78sZg3wpcfRlp20IUZqDdB/j9Z
            BmPwYkcSMzTksXuNEyFEmZUWlESPFSXg23wySvAthN17/uuS06p+sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T16:51:23Z"
    mac: ENC[AES256_GCM,data:8irGoXe2hrahwhvhKY4tHVgs/iB/3vgJ4idx8HGPJh42tMJz8mt19BqXsvT9B6FxttuG54A55snsT0dLrjMCjFcGEL0v9cHJeUes4udJBiq9YJNKfv2ae9c1vfOmZ4JZLFoiOE1xeVcNizkO/H75LAij979/KUgX0kwztE1ytgA=,iv:AOqvKWWz/bg3cCBMQWkt1XNFjFNipOXyA9IxB/H94yo=,tag:xVEvSJjHRQzjHEBB09q3Nw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
