apiVersion: ENC[AES256_GCM,data:QiU=,iv:g0mEhJgyXr0B63R7Y+b4Q/YQWZGMtOpVw21J6iUwAZA=,tag:u8/nl2uJq5Ybz37TV22iqA==,type:str]
kind: ENC[AES256_GCM,data:7RjYXCfm,iv:6+kFjhEMfYVE1fFITmX2hah39v4Jtxw1iNu61uvgQso=,tag:LHoqtI7RSMk6jFhcaPDN7Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6eYatXvtIpuNKS9CP6c=,iv:Syr0k6Hp3q5JFPsDMbUXllVzww2RYpc2LHzRD4K+9nc=,tag:CEP1eJ4ZQ9qm9i+kdTz7dA==,type:str]
    namespace: ENC[AES256_GCM,data:6JCytPpAK58=,iv:QgTG0+g6ZRM+QRHhPt8gZ8v9iijIDmhSkHPemJSOIXw=,tag:MAaSe//q0ChsmrBXg6MzYA==,type:str]
type: ENC[AES256_GCM,data:BrUqgidk,iv:8m1Oh8wYsmFtj/rpl2X30rvGVOjExSsCWcHNsG9ZgKQ=,tag:9p9hxkA0HRzMQiJ6lRCn+Q==,type:str]
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:gB5mxRkmYa5wGPA0SZYb4WG6nOA89cGx4Fg7kBOV016z30IulVFsvU8rzt5p42mA+r7Nv2swZif7KXpjTrJfqPqW5TSp2dA0,iv:jM07QWd3DEnM9S8ebYwDU4KcDMvfugikP/WEf+blNmo=,tag:7JMHqiHjuaZDd0SFZyCbqg==,type:str]
    GUILD_ID: ENC[AES256_GCM,data:hjUIOVM8K7nLcIPvkFVP4YNyAQ==,iv:vOr/CM0zMp+oYYgVSEEWwoTveLxq0WCGwJqTiGvkIZw=,tag:dkd+Vj2CbdZmKxLoHz/GhA==,type:str]
    TAILSCALE_KEY: ENC[AES256_GCM,data:3p316kujTAFKA+p/KAziKFgy6qhwefpfQQVY5HSHsTglFGkMjoB/OwS2u0VkFnygzQKv+tqHT3f7i4h1BQ==,iv:rOjxPXwoHx2a8ATbtVi3E4gazFsvVrBBk+rXU40MH4s=,tag:NgV8avbzeCw0/tLDEdG6Hg==,type:str]
    TAILNET_ID: ENC[AES256_GCM,data:0kRcYSQFGDq3vKnwGfpcLEs=,iv:KQv0LR+Nppa8GP8lOfkGrKedXt2ojcpyMdZ9DHYFfog=,tag:VprmJZJdMTcKzxx6i6xV9A==,type:str]
sops:
    age:
        - recipient: age1q4amzhu35vv98c8usgamjjhwhn5q82sulmzdmcdhkh2zq0a3vaesxvv9y4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzS3RpaVVCeWhOdDZwMG1z
            WjUrYjRucFQzano0a010Z3JGZVgxeXBYNHk0CjlxeFljdy9NOG5Xd3ZnbURoTDFu
            UkIzWWxiQWFaUWV4Y0djMERSL3hhNncKLS0tIE9pTmd6dGFBRzVYejI3OTlTMWxz
            VnJYd2Rnd1c5YjNjQnlxTHZ5T3ZRb0UKgdL3J2UG3ZtEOoaK/jFDokeB1/KGh2IB
            P1X5vq+KH+BI6ScWVJVy1uxTdCN0XcBWTgKpRXeDurevavFPP9nF0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1arllsk3da07lj6ers0cdvtaz4qqlg7lq7h8k7nmp2ejtwm29pgcs0lun67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OEFKaXBmT3BEd2VWckUy
            K0UyQTV6MytleDI2WVo3MTdNQ0FlcEp1OEVnClQ2SlQxcm9ZTkdiNDJrME9HUVdh
            RzNQSjdCbmhSN01EdUhqRDJBbGdIWmsKLS0tIG03Sm5ISno4eVhzUkI1dDNEY2Ji
            U2tNd1RhMHdUVDZZV0hMV2hSdEFMekUKtAzpcIu1LxbO4D/eyqCSIm7xfmTNcRjx
            AkekbCN/mvCAWZnYq1vsTmVu6FvvYP1AldpPkT+agbVG/2oxcPgiVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jksv6jmy6flf0cv3grctntgs7kp53c7d72690qsxrxvawxz7nu2sttfklz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTFdpSjlsYWNmOTFidytu
            cDBMQURRVkFSdEJUdkxzTWdwN0UwUlhySVdnCnZnSDk2cThnV0lIenNTS1E1NHNK
            RkRiRmNQU05LZ2Y5WkN5ampiblZHdVkKLS0tIFZ1anRZa0YyUlVyYmgydDNmc2ph
            OUlmVHppNUtUeU1CNWhhaURiYlhBNUkKPNhczZersKDbbo5yIm0p7haiu7Vb2/a3
            9hVRJk7UZeF7Ih6lsnHtmn/oKvCuGcMAcxkg9yYJmpAyXMns3Kx7LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19wdth3zh940spdq34gweu6feugejlzxeczlgjvf92nygg6tkf3lq2aprdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWmh1T1poODJnUU44UDdD
            ejlHU2g3QkdSeHh2YisrWWhOYXhEcTB4K0RnClYxaFhpUkhZaFh4TGJkS2RJYW1L
            R1Vwd2NmZ0tDb2M1bWQ5SUhZUGoxeW8KLS0tIFhYdzNWOTZGU3g5RTVGTzFVUVJl
            WUorS0JrK2JOZjJxNGdCOEdlNnZCMncKLtO33avUnTsFW6OlB/2PY72CdJ0HtH+g
            JzdehxTZlPW2k0cvIERG+hYjI6v+mqeOXGGHoWC371GHtCErV6jzCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T21:19:20Z"
    mac: ENC[AES256_GCM,data:mC1S0ZIbI94eGKy65QtsuH7Oo/oHagH5WH5FNcyG4Nw9ly5UDvFUyGSazKyitX2bGuKinofH7VCYofGLpvysiXNskR9Q6iksDIP1EZ4ufke0j+lc2RAmeVDObIvyG1ZB43sZZxzrEANqL6caIHG/KIS7owjt811xumX520/FMTI=,iv:jtDQLtEVful1xw699S1fZXaZlofqJQf1SDsEoG9VrIM=,tag:x8Mth9sr9khH65rzgpHuvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
