apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minecraft-rcon
  namespace: gaming
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rcon.cglavin50.com`)  # Change to your domain
      kind: Rule
      services:
        - name: minecraft-rcon-rcon-web-admin
          port: 80
  tls:
    store:
      name: default
      namespace: kube-system
