apiVersion: ENC[AES256_GCM,data:sS0=,iv:GwyQ8kee8DbKQAUnjPS40LZRVIa3MTxG8MdaCnUbgzE=,tag:cyo4JP+sXfAzldXsAfd5Rg==,type:str]
kind: ENC[AES256_GCM,data:V2aUm87C,iv:/B+BzRDPN2y6WW1Z0XX7FWw/s848UAgiEjCZtTc0pmE=,tag:1RSv1iRnQL24P9fWdzBd6w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uIVIwJ/9r0Sm7MzMDR/ApMjQcKEn,iv:WVEzlsDdi6EL7r53R4uZDtuW7Y3vHbY0v60J20hzLIc=,tag:iiJoM7qpheab+TV8KZnIDg==,type:str]
    namespace: ENC[AES256_GCM,data:kNDQGqBS,iv:lozHr6PJhDNS1/62jaD4S+aOSbxBKxZXYGt0xGXmRns=,tag:NXGwuw+OWlUKkPC3C5uEzA==,type:str]
type: ENC[AES256_GCM,data:kgt9RbOh,iv:yHiQgiSojQw51MzrdJpRQXc4wUQbUwMigcZzZaUMxL8=,tag:t18R6DX+aM4qzTkKukuYpw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:oaXAp/o=,iv:zwYdD+fYst5AgE2H/Elj5a+vslFymVoT5v9Bl7FaEHc=,tag:PsFwBlL+7I5iwALTGfAGUw==,type:str]
    rcon-password: ENC[AES256_GCM,data:xkFaNBc=,iv:AMnaJ+skTxe3FYdYTGkafcBYiuVSk+ELvLwKjjpE+aQ=,tag:OathC3EOXOsJGd5DyO4TwA==,type:str]
sops:
    age:
        - recipient: age1q4amzhu35vv98c8usgamjjhwhn5q82sulmzdmcdhkh2zq0a3vaesxvv9y4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NjlaYzZnSDM0QThkeUFz
            NDh0WnNOVllXNG14S1BxQkVIQUlFVTE0YlNBCmFpTUp3RFRialdJdTloMkpmY3Q3
            WXJkQU05Y1BqSzd4eXlUb2dSRkFUNlEKLS0tIG5DWEl2a1dZaTJYdU9FWnl3eUJy
            NGhRNUplQ3plYWlRMEtDdzZETVJ1bzQK5gG+So54dkqs/D4j8HtfDrEPmvR334Qg
            1OFG8m6AP+fAbthZ0R3YbXe/TeuoT6ZVsh+vXBuQjrZzFiXSvhwaNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1arllsk3da07lj6ers0cdvtaz4qqlg7lq7h8k7nmp2ejtwm29pgcs0lun67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN0k3Y2c4bStOSG9jK2w0
            QWpWK3ZqUy9OMEdYWmVHZnBSZkExKzNRUHpRCmVTaWVVTFV5U25XZjh5eEVDcnQr
            TlVNYkk4emkxRDJuaG9pdk44dDUvMmsKLS0tIGxwSHVWTm1RWHVhQ3VROTA0N3ZB
            RDFyM2w5eWIyYzQwSkVPaU8zeGNnaEkKPSoME4N7ZCgwIwyj7ePeM+Z6LX8vEls8
            D1JI8WdhScQMEl6DjWYZc2o6HdcmJLDAyWjZhT1xYxvNkXno9geUqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jksv6jmy6flf0cv3grctntgs7kp53c7d72690qsxrxvawxz7nu2sttfklz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWnJtTFBBRFBHSGhmd2Iz
            OTNkYlVpS3NrWjVHQkVSdW11RmdPV1d5OHo4CmQ2Um1oeS9xcFc0OHQvVlhWT3Bs
            NVRHTWxPdmJYTTUwY00rck1YU085ZE0KLS0tIG5LbS9oSnRJbkVray9zNFZ3Sk5l
            MllRWUhRdDBGTS9tdzRVQTY4R2dzUWsK0M0fffWSNHPB0qF5zGy3vc/wi4R0nb46
            r7l7t78bOheaeLxwa8dQY2a5HDHXW5H1VmMs2AeUBH8JmLBAt3yrVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19wdth3zh940spdq34gweu6feugejlzxeczlgjvf92nygg6tkf3lq2aprdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCR1RrbXNJRERJV1V5OFps
            SHpGVjdwc2U4Lzk1SnZqaUtVWHg3SFI4RTNFCkxUTFVpR0lWWkRDRklmT1RySFEx
            YTdieEFyb1I4eTJEd3ZYN0hTZ0xLMEUKLS0tIGhTMlBoNGV6eGpxN21abFYybFRz
            dUNRZy9PQmlGazlwd2g5aEpOdkI0aTgKuvUyGsXm92QWsqIr21qpTg69KPtS5cBd
            H5IugUBHbruVg7MVC6l+sKb7oXY1P67Ldtq3heDDE4QqdJ/TPbMePQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T03:58:00Z"
    mac: ENC[AES256_GCM,data:DVS9I5Ro4KJ5NltNkWpZie0Lmwg/BOjDc3vqIPQSyjNNh+h0ijUuF6mtll6iFzqgPrDeO4UBcBJXGdtXyew+9p3b+pzUc1s1DB6yXU4fyKeL7M3wGf9NjBeUaKwi63qoxeKClAwjXECoHwDq93VDnLolzLKfzRIce/nhS0LujKk=,iv:/149Gb9zMZQH4QpS63ukVPf+ZXoxZX+O7xHS0qxRq1I=,tag:l+7s+NXUy16Zr5roqstgkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
