apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: gaming
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft
      version: '4.x.x'  # Pin to a specific version or use a range
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: gaming
      interval: 12h
  values:
    # Minecraft server configuration
    minecraftServer:
      eula: true  # Accept EULA
      version: "LATEST"  # or specific version like "1.20.1"
      difficulty: normal
      whitelist: ""
      ops: ""
      motd: "Coops Minecraft Server :)"
      maxPlayers: 20
      viewDistance: 16
      gameMode: survival
      pvp: true
      serviceType: LoadBalancer  # or NodePort

      # mod configuration
      type: "FABRIC"  # VANILLA, SPIGOT, PAPER, FORGE, etc.
      fabricLauncherVersion: "LATEST"
      modrinth:
        projects:
          - lithium
          - krypton # help with rubberbanding
          - ferrite-core # memory usage
          - carpet
          # - servercore
          - c2me-fabric

          # gameplay mods
          # - simple-voice-chat

      rcon:
        enabled: true
        port: 25575
        existingSecret: minecraft-rcon-secret
        secretKey: rcon-password

        # Resource limits: 8gb + 5cores, burst to 12gi (no cpu limit)
    resources:
      requests:
        memory: 8Gi
        cpu: 5000m
      limits:
        memory: 12Gi
    
    # Persistence for world data
    persistence:
      dataDir:
        enabled: true
        size: 10Gi
        # storageClass: "local-path"  # Uncomment if you need specific storage class
