apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minecraft-server-charts
  namespace: gaming
spec:
  interval: 10m
  url: https://itzg.github.io/minecraft-server-charts/
