apiVersion: ENC[AES256_GCM,data:eMg=,iv:YDCCljbMTyfjYgzfspS2/BqimhEQSh6JXqHwbbvLqVI=,tag:tg72uiMUdlPL6olFVB5DZw==,type:str]
kind: ENC[AES256_GCM,data:DiGMNDpy,iv:nV6XtZS3mNEdOWBImyaVa81sO2VqUVsRFFG7ZJNduyA=,tag:kolt+9f4OlfKnBUX3NzcZA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JnSK+rGlRNJcQHWGIfQI23h9/D8=,iv:TO2DG+PPdKdAYau6Wv3CjFdd6x+yTshF96QDSV7uX8s=,tag:PeubeUrBjICCpulSr+f59Q==,type:str]
    namespace: ENC[AES256_GCM,data:mt96+ydauud+VZHQ,iv:I0heMpzDR6qUeQ+Ut4vhZ+q8w73QWJz3YqtIaSt4CCI=,tag:ovk+BelQguSNliZVJR7UTg==,type:str]
stringData:
    #ENC[AES256_GCM,data:kkW7mkEptHxHSpepa3oL2T8s,iv:xbZ5QpyiLeGjq1x6qrE47uCWnX6A7h9zdW3Mb0FsdxY=,tag:eLur+0Je+f9rJ99wMqA61g==,type:comment]
    api-token: ENC[AES256_GCM,data:USK5c9wlYZgwy5Up4JZU6NwfozQ99YO905RZRNLj4XtFRDlzPNzvEw==,iv:rkHyzadjqDqBvIfpbP+jjDow/v3/wsn1l/LVW+NkVKI=,tag:qR8KdzDqr7RgBjqp2l8VMw==,type:str]
sops:
    age:
        - recipient: age1q4amzhu35vv98c8usgamjjhwhn5q82sulmzdmcdhkh2zq0a3vaesxvv9y4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcmVtSUF0ZTZXWDQyclpZ
            SCswcjVmZG1FMUhMUUs4R0lZVUdlLzhacWs4CkxxR09QaFVPZDdYUVpZVkswSWxq
            NkJRakpXb1pyVTRSTkxTdlltcndsTXcKLS0tIGZlMDVjUXBzaUJqSVgwYW5KQWNC
            UmcvUGRKY3pHaGkrTXdmdElkc3UxQnMKcVqwUSL/1lVq5oNwXtg0MJHnFWaz3Nxg
            XcNSzZAoVdee6NIN08WC97VxVzNvLEUJplLpiA4da9pZOpABucXxFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1arllsk3da07lj6ers0cdvtaz4qqlg7lq7h8k7nmp2ejtwm29pgcs0lun67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WHdSWjlMWU9hdlYwUXJV
            YTBJcE1CNzg5TDg5OHJuRm9qY0laKzYxMGd3Cm02WmVHbGNIQmxpNEp0b2UrVm5E
            NGpNamdGMVZYRzVwYTNwbkNjdGtPejgKLS0tIG5SbEM2VHcwOWpJdjFoVWJKRmEx
            QlVYVDc2di95SXFQUW5nWitGbXJ1MlkKzcFtd2oYNjONoCis4eOwP+iAZxr/e5yQ
            CG5oJ8+MK1lsKAkNHPm5T4xYuGMoAYAPb16cqOcytxilO3PrZ02sAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jksv6jmy6flf0cv3grctntgs7kp53c7d72690qsxrxvawxz7nu2sttfklz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWUJXZnd4aHZRQ084MktO
            Q3pzTDMrdDVuemh1RGVzbXZhQmR0bzVxK25jCmZ4NFRGZmtPbFIwZnV5Z2R3REJS
            T1JVcURQR3JtcnNKUWx4ZjNEWE9wd3cKLS0tIEdRdG96ZE1wU01BeWxKeERsTExV
            cWNZQXNRdTJRakxvTzNRTFd5ZjR5ejQKl/EDGTvwv1h7UH2G2Pqe6g65oe4+vNNt
            0pOdsi/XdKR1uJUTqCOZR3fJxPEeBUBhVfvK2K4pYWM/4ZSDGefXgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19wdth3zh940spdq34gweu6feugejlzxeczlgjvf92nygg6tkf3lq2aprdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcG5YNHhOSzRIQTBzTVI4
            ZXpSTmZPU0d6dHBoc3cwNVJROGMyYWJzc244CjlNTWhRSlNGT0ZQUkgyRWVaOW1o
            K0tlTHZzTUZIUStsSTIvZjV6eGp4eW8KLS0tIFM3R1JpNXdSRTFzNWJUQmc4OWpU
            ZGY0U1hQUHNlVEU0WjR4WGpxZE1JODQKvslNuCHksC8R/oK6Dtojo1j4kb8UH29T
            +HYmqTDXJvoBH053jZZT43bLgKyex3XoYRenHTKHTx+b7f1+cYEV2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T00:39:49Z"
    mac: ENC[AES256_GCM,data:kJNhwFWWI4xGNBkcqNqEGU3cv2e6N1sNw4jBX2pk48cVBLyIJ99knCrMn4ccAC35VKDHT7a/5PAbC1Hz2UL+AVraZkSwahC0dkR0m6Fej9fbNk2JcZSOJFpvbb8/XjcVBxWzgQrLNmCbDS7xgblwWi068t4So3tmUMVAp2J8NJw=,iv:fKThdUxUxqOZAI+3HA+xxqsL7UmyM+YCaNUU90VDqfE=,tag:Q+yWfnTDGHqlAQtjes+YPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
