apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - source.yaml
  - release.yaml
  - cloudflare-secret.enc.yaml
  - letsencrypt-issuer.yaml
  - wildcard-cert.yaml
